name: Deploy to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH
        run: sudo apt-get install openssh-client -y

      - name: Create SSH dir
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
        
      - name: Copy SSH key
        run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key.pem && chmod 600 ~/.ssh/key.pem

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: ssh -i ~/.ssh/key.pem $USER@$HOST "mkdir my_dir"